### ISSUE TITLE
Nothing is appearing, based on master branch

### ISSUE THREAD

**Issue by bernardyip** [voythas/shine-unofficial#4]

**Comment by bernardyip** [comment]
Last commit working based on develop branch
b448f77489baaff35d15ab5b35b78fa088e1b61c

**Comment by voythas** [comment]
Yeah, I'm aware of a bug on the repo, it has been fixed in Webstore version, sorry for confusion. Can you install extension from there? Here's the link: https://chrome.google.com/webstore/detail/shine-for-reddit-unoffici/dlbccbcpelghmhkhmpefncahafgigkek

I will fix the bug on repo as soon as I get home, sorry!

**Comment by voythas** [comment]
Oh wait, I just checked again. It is not fixed, damn and I pushed it live.

**Comment by voythas** [comment]
Fixed.
